github.com:
    users:
        Sflores23:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Sflores23
